// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school.proto

package classes;

public interface ProfessorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:classes.Professor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 telephone = 3;</code>
   */
  int getTelephone();

  /**
   * <code>string birthDate = 4;</code>
   */
  java.lang.String getBirthDate();
  /**
   * <code>string birthDate = 4;</code>
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>string address = 5;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 5;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>repeated .classes.Student students = 6;</code>
   */
  java.util.List<classes.Student> 
      getStudentsList();
  /**
   * <code>repeated .classes.Student students = 6;</code>
   */
  classes.Student getStudents(int index);
  /**
   * <code>repeated .classes.Student students = 6;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .classes.Student students = 6;</code>
   */
  java.util.List<? extends classes.StudentOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .classes.Student students = 6;</code>
   */
  classes.StudentOrBuilder getStudentsOrBuilder(
      int index);
}
