// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school.proto

package classes;

/**
 * Protobuf type {@code classes.School}
 */
public  final class School extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:classes.School)
    SchoolOrBuilder {
private static final long serialVersionUID = 0L;
  // Use School.newBuilder() to construct.
  private School(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private School() {
    professors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new School();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private School(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              professors_ = new java.util.ArrayList<classes.Professor>();
              mutable_bitField0_ |= 0x00000001;
            }
            professors_.add(
                input.readMessage(classes.Professor.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        professors_ = java.util.Collections.unmodifiableList(professors_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return classes.ClassesProtobuf.internal_static_classes_School_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return classes.ClassesProtobuf.internal_static_classes_School_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            classes.School.class, classes.School.Builder.class);
  }

  public static final int PROFESSORS_FIELD_NUMBER = 1;
  private java.util.List<classes.Professor> professors_;
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  public java.util.List<classes.Professor> getProfessorsList() {
    return professors_;
  }
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  public java.util.List<? extends classes.ProfessorOrBuilder> 
      getProfessorsOrBuilderList() {
    return professors_;
  }
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  public int getProfessorsCount() {
    return professors_.size();
  }
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  public classes.Professor getProfessors(int index) {
    return professors_.get(index);
  }
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  public classes.ProfessorOrBuilder getProfessorsOrBuilder(
      int index) {
    return professors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < professors_.size(); i++) {
      output.writeMessage(1, professors_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < professors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, professors_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof classes.School)) {
      return super.equals(obj);
    }
    classes.School other = (classes.School) obj;

    if (!getProfessorsList()
        .equals(other.getProfessorsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProfessorsCount() > 0) {
      hash = (37 * hash) + PROFESSORS_FIELD_NUMBER;
      hash = (53 * hash) + getProfessorsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static classes.School parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static classes.School parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static classes.School parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static classes.School parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static classes.School parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static classes.School parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static classes.School parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static classes.School parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static classes.School parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static classes.School parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static classes.School parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static classes.School parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(classes.School prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code classes.School}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:classes.School)
      classes.SchoolOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return classes.ClassesProtobuf.internal_static_classes_School_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return classes.ClassesProtobuf.internal_static_classes_School_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              classes.School.class, classes.School.Builder.class);
    }

    // Construct using classes.School.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProfessorsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (professorsBuilder_ == null) {
        professors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        professorsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return classes.ClassesProtobuf.internal_static_classes_School_descriptor;
    }

    @java.lang.Override
    public classes.School getDefaultInstanceForType() {
      return classes.School.getDefaultInstance();
    }

    @java.lang.Override
    public classes.School build() {
      classes.School result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public classes.School buildPartial() {
      classes.School result = new classes.School(this);
      int from_bitField0_ = bitField0_;
      if (professorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          professors_ = java.util.Collections.unmodifiableList(professors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.professors_ = professors_;
      } else {
        result.professors_ = professorsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof classes.School) {
        return mergeFrom((classes.School)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(classes.School other) {
      if (other == classes.School.getDefaultInstance()) return this;
      if (professorsBuilder_ == null) {
        if (!other.professors_.isEmpty()) {
          if (professors_.isEmpty()) {
            professors_ = other.professors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProfessorsIsMutable();
            professors_.addAll(other.professors_);
          }
          onChanged();
        }
      } else {
        if (!other.professors_.isEmpty()) {
          if (professorsBuilder_.isEmpty()) {
            professorsBuilder_.dispose();
            professorsBuilder_ = null;
            professors_ = other.professors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            professorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProfessorsFieldBuilder() : null;
          } else {
            professorsBuilder_.addAllMessages(other.professors_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      classes.School parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (classes.School) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<classes.Professor> professors_ =
      java.util.Collections.emptyList();
    private void ensureProfessorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        professors_ = new java.util.ArrayList<classes.Professor>(professors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        classes.Professor, classes.Professor.Builder, classes.ProfessorOrBuilder> professorsBuilder_;

    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public java.util.List<classes.Professor> getProfessorsList() {
      if (professorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(professors_);
      } else {
        return professorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public int getProfessorsCount() {
      if (professorsBuilder_ == null) {
        return professors_.size();
      } else {
        return professorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public classes.Professor getProfessors(int index) {
      if (professorsBuilder_ == null) {
        return professors_.get(index);
      } else {
        return professorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder setProfessors(
        int index, classes.Professor value) {
      if (professorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorsIsMutable();
        professors_.set(index, value);
        onChanged();
      } else {
        professorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder setProfessors(
        int index, classes.Professor.Builder builderForValue) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.set(index, builderForValue.build());
        onChanged();
      } else {
        professorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder addProfessors(classes.Professor value) {
      if (professorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorsIsMutable();
        professors_.add(value);
        onChanged();
      } else {
        professorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder addProfessors(
        int index, classes.Professor value) {
      if (professorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProfessorsIsMutable();
        professors_.add(index, value);
        onChanged();
      } else {
        professorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder addProfessors(
        classes.Professor.Builder builderForValue) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.add(builderForValue.build());
        onChanged();
      } else {
        professorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder addProfessors(
        int index, classes.Professor.Builder builderForValue) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.add(index, builderForValue.build());
        onChanged();
      } else {
        professorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder addAllProfessors(
        java.lang.Iterable<? extends classes.Professor> values) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, professors_);
        onChanged();
      } else {
        professorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder clearProfessors() {
      if (professorsBuilder_ == null) {
        professors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        professorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public Builder removeProfessors(int index) {
      if (professorsBuilder_ == null) {
        ensureProfessorsIsMutable();
        professors_.remove(index);
        onChanged();
      } else {
        professorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public classes.Professor.Builder getProfessorsBuilder(
        int index) {
      return getProfessorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public classes.ProfessorOrBuilder getProfessorsOrBuilder(
        int index) {
      if (professorsBuilder_ == null) {
        return professors_.get(index);  } else {
        return professorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public java.util.List<? extends classes.ProfessorOrBuilder> 
         getProfessorsOrBuilderList() {
      if (professorsBuilder_ != null) {
        return professorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(professors_);
      }
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public classes.Professor.Builder addProfessorsBuilder() {
      return getProfessorsFieldBuilder().addBuilder(
          classes.Professor.getDefaultInstance());
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public classes.Professor.Builder addProfessorsBuilder(
        int index) {
      return getProfessorsFieldBuilder().addBuilder(
          index, classes.Professor.getDefaultInstance());
    }
    /**
     * <code>repeated .classes.Professor professors = 1;</code>
     */
    public java.util.List<classes.Professor.Builder> 
         getProfessorsBuilderList() {
      return getProfessorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        classes.Professor, classes.Professor.Builder, classes.ProfessorOrBuilder> 
        getProfessorsFieldBuilder() {
      if (professorsBuilder_ == null) {
        professorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            classes.Professor, classes.Professor.Builder, classes.ProfessorOrBuilder>(
                professors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        professors_ = null;
      }
      return professorsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:classes.School)
  }

  // @@protoc_insertion_point(class_scope:classes.School)
  private static final classes.School DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new classes.School();
  }

  public static classes.School getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<School>
      PARSER = new com.google.protobuf.AbstractParser<School>() {
    @java.lang.Override
    public School parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new School(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<School> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<School> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public classes.School getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

