// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school.proto

package classes;

public interface SchoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:classes.School)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  java.util.List<classes.Professor> 
      getProfessorsList();
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  classes.Professor getProfessors(int index);
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  int getProfessorsCount();
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  java.util.List<? extends classes.ProfessorOrBuilder> 
      getProfessorsOrBuilderList();
  /**
   * <code>repeated .classes.Professor professors = 1;</code>
   */
  classes.ProfessorOrBuilder getProfessorsOrBuilder(
      int index);
}
